### ISSUE TITLE
Interactive sliders fail to load in JupyterLab

### ISSUE THREAD

**Issue by pibion** [villano-lab/galactic-spin-W1#33]
I am submitting a **bug report**.

**This bug occurs in:**
environment.yml

**Expected behavior:**
I should be able to see the interactive sliders in JupyterLab.  

**Current behavior:**
Instead, I get a javascript error where the sliders and plot should be if I open a notebook in JupyterLab 3.6.2.  The sliders and plot work fine in JupyterNotebook 6.5.3

**Steps to reproduce:**
1. Update Anaconda, which puts JupyterLab at 3.6.2
2. Launch JupyterLab
3. Open binder/02_Widget_NGC5533_DMonly.ipynb
4. Click Kernel>"Restart Kernel and Run all Cells"
5. Scroll down to see the error message

**Other Information:**
Maybe this isn't a bug and the expectation is that these notebooks only work on JupyterNotebook?  If so I missed this in the documentation.  

I made a fork at that updates the ipywidets version and this works locally on both JupyterNotebook 6.5.3 and JupyterLab 3.6.2, but I haven't tested it successfully on binder yet - the build fails.  See https://mybinder.org/v2/gh/pibion/galactic-spin-W1/ipywidgets-update.  The fork is at https://github.com/pibion/galactic-spin-W1 and the change is on the branch ipywidgets-update.

**Comment by nuclearGoblin** [comment]
Definitely a bug; it should work in either environment. The build issue you're encountering on Binder looks like an issue with the [`postBuild`](https://github.com/villano-lab/galactic-spin-W1/blob/master/binder/postBuild) script. When you run locally, how do you install those two extensions -- or do the notebooks run without them?
