### ISSUE TITLE
Create Dockerfile for running notebooks

### ISSUE THREAD

**Issue by nuclearGoblin** [villano-lab/galactic-spin-W1#5]
As discussed in #1, a dockerfile would allow us more control over the Binder environment and could be used in testing so that the Binder and testing environments are identical. This may also prove useful for deployment at workshops or similar settings in the future and for users familiar with docker (although presently, the environment yaml file is almost definitely enough).

**Comment by nuclearGoblin** [comment]
[repo2docker](https://repo2docker.readthedocs.io/en/latest/) is the mechanism used by mybinder.org to convert a repository into a docker image. So, we should attempt to use this in testing to get the most consistent possible results.

**Comment by nuclearGoblin** [comment]
@villaa would it be an option to add this repository to another ci site? According to [this documentation](https://repo2docker.readthedocs.io/en/latest/howto/deploy.html), we could deploy the same way that binder does to CircleCI and run tests there. This seems much more straightforward than constructing a docker image ourselves, and serves the same purpose while allowing us to continue using any upgrades made to the default binder environment.

**Comment by villaa** [comment]
> @villaa would it be an option to add this repository to another ci site? According to [this documentation](https://repo2docker.readthedocs.io/en/latest/howto/deploy.html), we could deploy the same way that binder does to CircleCI and run tests there. This seems much more straightforward than constructing a docker image ourselves, and serves the same purpose while allowing us to continue using any upgrades made to the default binder environment.

Hey @nuclearGoblin this is a great idea.  Also it will give us some  experience with another CI system, it was mentioned previously (for the review of our other paper)  that Travis CI is costly; is CircleCI free?

**Comment by nuclearGoblin** [comment]
> Hey @nuclearGoblin this is a great idea.  Also it will give us some  experience with another CI system, it was mentioned previously (for the review of our other paper)  that Travis CI is costly; is CircleCI free?

They do seem to have a free tier, which gives "6,000 free build minutes per month." Our tests for this repository take ~20 minutes, which would give us 300 builds/month. Our last 25 travis builds were over the course of 8 days, so we can approximate our monthly number of builds at 100. So I think the free tier could reasonably be expected to cover our builds.
