### ISSUE TITLE
JOSE Paper v1 update

### ISSUE THREAD

**Issue by villaa** [villano-lab/galactic-spin-W1#8]
Need to get a reasonable draft in so people can start going over it in detail.

**Comment by nuclearGoblin** [comment]
~~- [ ] Update references to individual modules in the file `paper/module_overview.jpg`.~~ We will still be working on this, but this figure is no longer needed for the paper.
- [x] Discuss how notebooks are delivered to students.
- [x] "Describe the submission and explain its eligibility for JOSE" (see https://openjournals.readthedocs.io/en/jose/submitting.html)
- [x] "Describ[e] how [the modules] might be adopted by others."
- [x] "For learning modules, describe the... instructional design."
- [x] "Cite... a link to the open archive of the sofware or the learning module."
- [X] Shorten paper to <1k words
- [x] Replace all reference placeholders
- [x] Move figure(s) in the `paper` directory that will not be used for this paper to a better location
